spring.application.name=ThrillZone-Park
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/amusement_park_db
spring.datasource.username=park_admin
spring.datasource.password=sagar
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect